config/routes.rb
Rails.application.routes.draw do
  resources :trials
  get 'static_pages/warehouse'
  get 'static_pages/index'
  get 'trials/index'
  
  get 'static_pages/home'
  get 'static_pages/q1'
  get 'static_pages/q2'
  get 'static_pages/q3'
  get 'static_pages/q4'
  get 'static_pages/q5'
  get 'static_pages/q6'
  get 'static_pages/q7'
  get 'static_pages/q8'
  get 'static_pages/q9'
  get 'static_pages/result'

  resources :trials

  root 'static_pages#home'

end

app/models/trial.rb
class Trial < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def hello
    render text: "hello,wordl!"
  end
  
  
  
  
  
  
  
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def warehouse
  end
end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  before_action :set_trial, only: [:show, :edit, :update, :destroy]

  # GET /trials
  # GET /trials.json
  def index
    @trials = Trial.all
  end
  
  def warehouse
    @trials=Trial.all
  end
  

  # GET /trials/1
  # GET /trials/1.json
  def show
  end

  # GET /trials/new
  def new
    @trial = Trial.new
  end

  # GET /trials/1/edit
  def edit
  end

  # POST /trials
  # POST /trials.json
  def create
    @trial = Trial.new(trial_params)

    respond_to do |format|
      if @trial.save
        format.html { redirect_to @trial, notice: 'Trial was successfully created.' }
        format.json { render :show, status: :created, location: @trial }
      else
        format.html { render :new }
        format.json { render json: @trial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trials/1
  # PATCH/PUT /trials/1.json
  def update
    respond_to do |format|
      if @trial.update(trial_params)
        format.html { redirect_to @trial, notice: 'Trial was successfully updated.' }
        format.json { render :show, status: :ok, location: @trial }
      else
        format.html { render :edit }
        format.json { render json: @trial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trials/1
  # DELETE /trials/1.json
  def destroy
    @trial.destroy
    respond_to do |format|
      format.html { redirect_to trials_url, notice: 'Trial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trial
      @trial = Trial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trial_params
      params.require(:trial).permit(:name, :timestamp, :answer, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChartApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
開始前ページ<br>
名前を入力し、開始ボタンを押してください
<br><br>

<%
sta=""
url=request.url
if(url.index("static_pages")==nil)
  sta="static_pages/"
end
%>


<form method="get" action="<%=sta%>q1">

<a class="btn btn02"><p>名前：<input type="text" name="name"></p></a>
<p><input type="submit" value="開始"></p>

</form>

<%

require "date"

url=request.url

if(url.index("text1=")!=nil)
  
  index_point=url.index("text1=")+6
  index_point2=url.index("&text2=")+7
  
  i=index_point
  text=""
  while(i<index_point2-7)
    text=text.to_s+url[i].to_s
    i=i+1
  end
  
  text=URI.unescape(text)

  i=index_point2
  ans=""
  while url[i]!="A" do
    ans=ans+url[i].to_s
    i=i+1
  end
  
  i=i+1
  name=""
  while url[i]!=nil do
    name=name+url[i].to_s
    i=i+1
  end
  name=URI.unescape(name)
  name=URI.unescape(name)

  
  nt=Trial.new
  
  nowTime=DateTime.now
  nt.timestamp=nowTime
  nt.name=name
  nt.answer=ans
  nt.text=text
  
  nt.save!

end

%>

app/views/static_pages/q1.html.erb
<%
url=request.url
index_point=url.index("name=")+5
i=index_point
name=""
while(url[i]!=nil)
  name=name.to_s+url[i].to_s
  i=i+1
end
%>



<a class="que">Q.阿氐河荘において、多くの村や田畑が失われ、人がいなくなったのはなぜでしょうか？</a>
<br><br>
<a href=<%="q4?1XXA"+name%> class="btn btn03">地頭の治め方が悪いために百姓が逃げて、土地や田畑が荒れた</a><br>
<br>
<a href=<%="q2?2A"+name%> class="btn btn03">洪水や台風などの災害が起きて、村やその田畑が減った</a><br>
<br>
<a href=<%="q3?3XA"+name%> class="btn btn03">地頭が攻め滅ぼして、村やその田畑が減った</a><br>

app/views/static_pages/q2.html.erb
<a class="que">Q.災害が起きて村やその田畑が減った場合、責任を問われるのは誰でしょうか？</a>
<br>
<%
url=request.url

i=0
while url[i]!="?" do
  i=i+1
end
i=i+1

ans=""
while url[i]!="A" do
  ans=ans+url[i].to_s
  i=i+1
end

i=i+1

name=""
while url[i]!=nil do
  name=name+url[i].to_s
  i=i+1
end

%>
<br>
<a class="btn btn03" href="result?<%=ans+"1XXXXXXX"%>A<%=name%>">幕府</a><br><br>
<a class="btn btn03" href="q4?<%=ans+"2X"%>A<%=name%>">地頭</a><br><br>
<a class="btn btn03" href="q4?<%=ans+"3X"%>A<%=name%>">村人</a><br><br>
<a class="btn btn03" href="q4?<%=ans+"4X"%>A<%=name%>">誰も責任を問われない</a><br><br>

app/views/static_pages/q3.html.erb
<a class="que">Q.地頭が村を攻め滅ぼしたのはなぜでしょうか？</a>
<br>
<%
url=request.url

i=0
while url[i]!="?" do
  i=i+1
end
i=i+1

ans=""
while url[i]!="A" do
  ans=ans+url[i].to_s
  i=i+1
end

i=i+1


name=""
while url[i]!=nil do
  name=name+url[i].to_s
  i=i+1
end

%>
<br>
<a class="btn btn03" href="q4?<%=ans+"1"%>A<%=name%>">その村が悪い村だったから</a><br><br>
<a class="btn btn03" href="q4?<%=ans+"2"%>A<%=name%>">略奪目的</a><br><br>

app/views/static_pages/q4.html.erb
<a class="que">Q.村の土地や田畑が荒れたため、地頭の指示のもと復興が行われました。どれだけの人が地頭に従ったでしょうか？</a>
<br>
<%
url=request.url

i=0
while url[i]!="?" do
  i=i+1
end
i=i+1

ans=""
while url[i]!="A" do
  ans=ans+url[i].to_s
  i=i+1
end

i=i+1


name=""
while url[i]!=nil do
  name=name+url[i].to_s
  i=i+1
end

%>
<br>
<a class="btn btn03" href="result?<%=ans+"1XXXXX"%>A<%=name%>">すべて</a><br><br>
<a class="btn btn03" href="q5?<%=ans+"2"%>A<%=name%>">半々</a><br><br>
<a class="btn btn03" href="q5?<%=ans+"3"%>A<%=name%>">従う村人はいなかった</a><br><br>

app/views/static_pages/q5.html.erb
<a class="que">Q.地頭の指示に従わなかった村人は、なぜ従わなかったのでしょうか？</a>
<br>
<%
url=request.url

i=0
while url[i]!="?" do
  i=i+1
end
i=i+1

ans=""
while url[i]!="A" do
  ans=ans+url[i].to_s
  i=i+1
end

i=i+1

name=""
while url[i]!=nil do
  name=name+url[i].to_s
  i=i+1
end

%>
<br>
<a class="btn btn03" href="q6?<%=ans+"1"%>A<%=name%>">地頭の悪行に耐えられず、復興どころではないから</a><br><br>
<a class="btn btn03" href="q6?<%=ans+"2"%>A<%=name%>">実は地頭の敵対勢力と裏取引をしていて、ストライキをすることで見返りを貰っている</a><br><br>
<a class="btn btn03" href="q6?<%=ans+"3"%>A<%=name%>">村人同士でも争っていて、そのうち地頭を信用していない派閥だから</a><br><br>

app/views/static_pages/q6.html.erb
<a class="que">Q.地頭の指示に従わなかった村人は、地頭の指示に従う村人にたいして、どのように接したでしょうか？</a>
<br>
<%
url=request.url

i=0
while url[i]!="?" do
  i=i+1
end
i=i+1

ans=""
while url[i]!="A" do
  ans=ans+url[i].to_s
  i=i+1
end

i=i+1

name=""
while url[i]!=nil do
  name=name+url[i].to_s
  i=i+1
end

%>
<br>
<a class="btn btn03" href="q7?<%=ans+"1"%>A<%=name%>">対立し、時には傷つけ、殺すこともあった</a><br><br>
<a class="btn btn03" href="q7?<%=ans+"2"%>A<%=name%>">対立し、村八分にした</a><br><br>
<a class="btn btn03" href="q7?<%=ans+"3"%>A<%=name%>">それまで通りに接した</a><br><br>

app/views/static_pages/q7.html.erb
<a class="que">Q.地頭のいう「耳を切り、鼻を削ぎ……」とは、いかなる意図の言葉でしょうか？</a>
<br>
<%
url=request.url

i=0
while url[i]!="?" do
  i=i+1
end
i=i+1

ans=""
while url[i]!="A" do
  ans=ans+url[i].to_s
  i=i+1
end

i=i+1

name=""
while url[i]!=nil do
  name=name+url[i].to_s
  i=i+1
end

%>
<br>
<a class="btn btn03" href="q8?<%=ans+"1"%>A<%=name%>">ある罪に対して定められた刑罰</a><br><br>
<a class="btn btn03" href="q8?<%=ans+"2"%>A<%=name%>">地頭が恐怖で押さえつけるための脅迫</a><br><br>

app/views/static_pages/q8.html.erb
<a class="que">Q.カタカナ書き訴状の内容を考えたのは誰でしょうか？</a>
<br>
<%
url=request.url

i=0
while url[i]!="?" do
  i=i+1
end
i=i+1

ans=""
while url[i]!="A" do
  ans=ans+url[i].to_s
  i=i+1
end

i=i+1

name=""
while url[i]!=nil do
  name=name+url[i].to_s
  i=i+1
end

%>
<br>
<a class="btn btn03" href="q9?<%=ans+"1"%>A<%=name%>">村人</a><br><br>
<a class="btn btn03" href="q9?<%=ans+"2"%>A<%=name%>">阿氐河荘の外の人</a><br><br>

app/views/static_pages/q9.html.erb
<a class="que">Q.このカタカナ書き訴状による裁判について、「地頭が裁かれた」という記録が残っていません。それはなぜでしょうか？</a>
<br>
<%
url=request.url

i=0
while url[i]!="?" do
  i=i+1
end
i=i+1

ans=""
while url[i]!="A" do
  ans=ans+url[i].to_s
  i=i+1
end

i=i+1

name=""
while url[i]!=nil do
  name=name+url[i].to_s
  i=i+1
end

%>
<br>
<a class="btn btn03" href="result?<%=ans+"1"%>A<%=name%>">村人の訴えの正当性が認められず、裁判にならなかったから</a><br><br>
<a class="btn btn03" href="result?<%=ans+"2"%>A<%=name%>">地頭が申し開きをせず、裁判にならないまま自ら罰を受けたから</a><br><br>
<a class="btn btn03" href="result?<%=ans+"3"%>A<%=name%>">地頭が訴状をもみ消したから</a><br><br>

app/views/static_pages/result.html.erb
<a class="btn btn01">[結果]
<%
url=request.url

i=0
while url[i]!="?" do
  i=i+1
end
i=i+1

ans=""
while url[i]!="A" do
  ans=ans+url[i].to_s
  i=i+1
end

i=i+1


name=""
while url[i]!=nil do
  name=name+url[i].to_s
  i=i+1
end

%>
<br>
<%
text=""
case ans[0]
when "1" then
  text=text+"阿氐河荘の地頭は統治者として優れているとは言い難く、多くの人がやっていられないとその土地を離れていきました。当然、田畑は手入れがされず、荒れていきました。"
when "2" then
  text=text+"阿氐河荘を突如自然災害が襲い、多くの人、田畑が失われました。"
when "3" then
  text=text+"阿氐河荘の地頭が村を武力で襲い、田畑も荒らされました。"
when "4" then
  text=text+""
else
  text=text+""
end

case ans[1]
when "1" then
  text=text+"その被害についての責任は幕府が負い、阿氐河荘に充分な援助を行いました。まして、訴状が書かれるなんてことも起こりませんでした。"
when "2" then
  text=text+"その被害についての責任は地頭が負い、皆で復興しなければならなくなりました。"
when "3" then
  text=text+"その被害についての責任は村人が負い、皆で復興しなければならなくなりました。"
when "4" then
  text=text+"自然災害の責任など誰が取るわけでもなく、当事者である阿氐河荘の人々により復興されることになりました。"
else
  text=text+""
end

case ans[2]
when "1" then
  text=text+"不正や年貢の滞納を重ねた村々は地頭の手で裁かれ、終わってみれば残る村は少なくなっていました。阿氐河荘の民度が低すぎたのです。そして復興に人手が必要になり、これまで地頭に従ってきた村人への負担が増すことになってしまいました。"
when "2" then
  text=text+"地頭は私利私欲による略奪を重ね、終わってみれば残る村は少なくなってしまいました。大々的な立て直しが必要になるほど荒らすとは……。"
when "3" then
  text=text+"3"
when "4" then
  text=text+""
else
  text=text+""
end

case ans[3]
when "1" then
  text=text+"残った村人たちは地頭に従い、力を合わせ復興に励みました。まして、訴状が書かれるなんてことも起こりませんでした。"
when "2" then
  text=text+"残った村人たちは、地頭に従うかどうかで分かれました。"
when "3" then
  text=text+"残った村人たちのうち、地頭に従う村人はいませんでした。"
when "4" then
  text=text+""
else
  text=text+""
end

case ans[4]
when "1" then
  text=text+"「阿氐河荘は地頭の暴虐で荒れ放題。真面目に復興をする余裕なんてない！」そう言って、一部の村人は地頭から離れていったのです。"
when "2" then
  text=text+"宗教関係で地頭と対立する勢力が、これを期に地頭を陥れようと、報酬をちらつかせて村人に根回しをしていました。ただでさえ村人は貧しいため、次々に引き込まれていきました。"
when "3" then
  text=text+"そもそも村人たちも一枚岩ではありません。これまでも地頭をよく思っていなかった村人たちは、「地頭のやろうめ、とうとう天罰が下ったんだろうよ。いい気味だ」なんて思って、復興指示に無視を決め込みました。"
when "4" then
  text=text+""
else
  text=text+""
end

case ans[5]
when "1" then
  text=text+"村人同士の対立は深まり、ちょっとしたケンカはもちろん、刃傷沙汰や、魔女狩りめいためちゃくちゃな村内裁判で死人まで出る始末。"
when "2" then
  text=text+"村人同士の対立は深まり、反地頭派は復興に手を貸さないどころか、地頭に従う村人に対して冷たく接し、日常生活の部分においても一切の手助けをしませんでした。"
when "3" then
  text=text+"地頭について思うところはあれど、同じ村人。復興指示に従わない村人たちも、日常生活の面では今まで通りに過ごし、助け合いました。"
when "4" then
  text=text+""
else
  text=text+""
end

case ans[6]
when "1" then
  text=text+"復興に参加してくれない村人たちに対し、地頭は「従わなければ家のものには刵刑・劓刑が適用されるぞ」と警告しました。"
when "2" then
  text=text+"復興に参加してくれない村人たちに対し、地頭は「従わなければ家のものの耳を切り落とし、鼻も削いでやるぞ！」と脅しました。"
when "3" then
  text=text+"3"
when "4" then
  text=text+""
else
  text=text+""
end

case ans[7]
when "1" then
  text=text+"そんな中、反地頭派の村人たちが地頭を訴えようと訴状を書きました。村人の視点で書かれたため、客観的とは言い切れない内容ですが、最後まで書き上げられました。"
when "2" then
  text=text+"そんな中、地頭の敵対勢力が村人をそそのかして訴状を書かせ、裁判を起こさせようと動き始めました。もちろん、訴状の内容は村人ではなくよそ者が整理した内容で、村人はそれに従って書いただけです。"
when "3" then
  text=text+"3"
when "4" then
  text=text+""
else
  text=text+""
end

case ans[8]
when "1" then
  text=text+"訴状は六波羅探題に提出されたものの、当時同じような村人の訴えが多くある中、阿氐河荘の訴状については村人の主張の正当性が認められず、起訴材料が不足であるとして裁判は起こりませんでした。そんなこともあって、訴状だけが現代に残り、裁判についての資料なんて見つかろうはずがありませんでした。"
when "2" then
  text=text+"訴状は受理され、地頭はなんと一切の弁解を行わないまま、阿氐河荘を去っていきました。そんなこともあって、裁判の記録が作られることはありませんでした。"
when "3" then
  text=text+"地頭は手をつくして訴状をもみ消しました。……しかしそうすると、今教科書に載っているこの訴状は一体なんなのでしょうか？地頭が訴状を抹消して罪を逃れたならば、訴状が残っているはずがありません。
"
when "4" then
  text=text+""
else
  text=text+""
end

%>
<%=text%>
</a>
<br><br>
今回の回答に対する以上の結果について、矛盾点や感想等を入力してください。
<form method="get" action="home">
<textarea name="text1" cols="50" rows="10"></textarea>
<!--<textarea name="text2" cols="1" rows="0" readonly><%#=ans+"A"+name%></textarea>-->
<input type="hidden" name="text2" value="<%=ans+"A"+name%>">
<p><input type="submit" value="今回の回答を終了する">
</form>

app/views/static_pages/warehouse.html.erb
<table>
  <thead>
    <tr>
      <th>リスト</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tr>
      <th>名前</th>
      <th>終了時刻</th>
      <th>回答</th>
      <th>記述</th>
      <th colspan="3"></th>
  </tr>
  <tbody>
    <% @trials.each do |trial| %>
      <tr>
        <td><%= trial.name %></td>
        <td><%= trial.timestamp %></td>
        <td><%= trial.answer %></td>
        <td><%= trial.text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trials/_form.html.erb
<%= form_for(@trial) do |f| %>
  <% if @trial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trial.errors.count, "error") %> prohibited this trial from being saved:</h2>

      <ul>
      <% @trial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trials/edit.html.erb
<h1>Editing Trial</h1>

<%= render 'form' %>

<%= link_to 'Show', @trial %> |
<%= link_to 'Back', trials_path %>

app/views/trials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Timestamp</th>
      <th>Answer</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trials.each do |trial| %>
      <tr>
        <td><%= trial.name %></td>
        <td><%= trial.timestamp %></td>
        <td><%= trial.answer %></td>
        <td><%= trial.text %></td>
        <td><%= link_to 'Show', trial %></td>
        <td><%= link_to 'Edit', edit_trial_path(trial) %></td>
        <td><%= link_to 'Destroy', trial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trial', new_trial_path %>

app/views/trials/new.html.erb
<h1>New Trial</h1>

<%= render 'form' %>

<%= link_to 'Back', trials_path %>

app/views/trials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trial.name %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @trial.timestamp %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @trial.answer %>
</p>

<p>
  <strong>Text:</strong>
  <%= @trial.text %>
</p>

<%= link_to 'Edit', edit_trial_path(@trial) %> |
<%= link_to 'Back', trials_path %>